base_url = "https://portal.getpaidinbitcoin.com.au"
login_url = "/account/login"
reset_password_url = "/Account/ForgotPassword"
reset_confirmation_url = "/Account/ForgotPasswordConfirmation"
dashboard_url = "/Dashboard"
test_user = "alice@getpaidinbitcoin.com.au"
test_password = "Test1234"
